# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  apm: {}
  #    name: newrelic
  #    image:
  #      repository: 10.11.240.41:5000/joann-brereton-gmail-com/demo
  #      tag: 0.0.8
  config:
    envKv:
      # springboot
      SPRING_PROFILES_ACTIVE: stage
      _JAVA_OPTIONS: >
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -Dsun.zip.disableMemoryMapping=true
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=5
        -XX:MaxHeapFreeRatio=10
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Xms10m
        -Xmx192m

replicaCount: 1
image:
  repository: 10.11.240.41:5000/joann-brereton-gmail-com/demo
  tag: 0.0.8
  pullPolicy: IfNotPresent
service:
  name: demo
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10